// <auto-generated />
using System;
using CinemaInformationSystemRepository.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaInformationSystemRepository.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20220629122952_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaInformationSystemRepository.Entities.Auditorium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceCount")
                        .HasColumnType("int");

                    b.Property<int>("RowSeatCount")
                        .HasColumnType("int");

                    b.Property<int>("RowsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MovieId");

                    b.ToTable("Auditoriums");
                });

            modelBuilder.Entity("CinemaInformationSystemRepository.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Age")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CinemaInformationSystemRepository.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("ClientMovie", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WachedMoviesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientsId", "WachedMoviesId");

                    b.HasIndex("WachedMoviesId");

                    b.ToTable("ClientMovie");
                });

            modelBuilder.Entity("CinemaInformationSystemRepository.Entities.Auditorium", b =>
                {
                    b.HasOne("CinemaInformationSystemRepository.Entities.Client", null)
                        .WithMany("UsedAuditoriums")
                        .HasForeignKey("ClientId");

                    b.HasOne("CinemaInformationSystemRepository.Entities.Movie", null)
                        .WithMany("Auditorium")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("ClientMovie", b =>
                {
                    b.HasOne("CinemaInformationSystemRepository.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaInformationSystemRepository.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("WachedMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaInformationSystemRepository.Entities.Client", b =>
                {
                    b.Navigation("UsedAuditoriums");
                });

            modelBuilder.Entity("CinemaInformationSystemRepository.Entities.Movie", b =>
                {
                    b.Navigation("Auditorium");
                });
#pragma warning restore 612, 618
        }
    }
}
